Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,

Logistic Regression,
SVM,
Decision Tree,
Random Forest

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()

In [3]:
from sklearn.model_selection import cross_val_score


# Logistic Regression score

In [15]:
lr=cross_val_score(LogisticRegression(), iris.data, iris.target,cv=3)
lr


C:\Users\aakri\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.98, 0.96, 0.98])

In [18]:
np.average(lr)


0.9733333333333333

# SVM score

In [19]:
svc=cross_val_score(SVC(), iris.data, iris.target,cv=3)
svc


array([0.96, 0.98, 0.94])

In [20]:
np.average(svc)


0.96

# Decision Tree score

In [28]:
d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target,cv=3)
d_scores

array([0.98, 0.92, 1.  ])

In [29]:
np.average(d_scores)


0.9666666666666667

# Random Forest score

In [30]:
r = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target,cv=3)
r

array([0.98, 0.94, 0.96])

In [31]:
np.average(r)


0.96

## Best performed by Linear Regression